---
apiVersion: v1
kind: Namespace
metadata:
  name: labs
---
apiVersion: v1
kind: Namespace
metadata:
  name: labs-2
---
apiVersion: v1
kind: Namespace
metadata:
  name: labs-3

---
apiVersion: v1
kind: Namespace
metadata:
  name: labs-4
