apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: labs
  labels:
    app: nginx
spec:
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', 'echo The app is running! && sleep 10']
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: webserver
      image: crccheck/hello-world