apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: nginx:1.16.1
          envFrom:
          - configMapRef:
               name: nginx-config
          - secretRef:
               name: nginx-secret
          ports:
            - containerPort: 80
