apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-jetlir
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argo-cd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: nginx-jetlir
spec:
  # The project the application belongs to.
  project: argocdjetlir

  # Source of the application manifests
  source:
    repoURL: git@github.com:jetlirgashi/argocd-apps.git
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: argocd-apps/directory  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git

    # # directory
    directory:
      recurse: true  
      # To match multiple patterns, wrap the patterns in {} and separate them with commas. For example: '{*.yml,*.yaml}'
      include: '*.yaml'

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://kubernetes.default.svc  
    namespace: argocdjetlir
    
  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).