name: build-publish-ecr
on:
  push:
    branches: ["main"]
    paths: 
       - 'nextjs/nextjs-app/**'
  workflow_dispatch:

jobs:
  build-publish-ecr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      working-directory: nextjs/nextjs-app
      run: npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build the Docker image and push to AWS ECR
      working-directory: nextjs/nextjs-app
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}-$(git rev-parse --short "$GITHUB_SHA")
        docker build -t nextjs:$IMAGE_TAG .
        docker tag nextjs:$IMAGE_TAG 313422618945.dkr.ecr.eu-central-1.amazonaws.com/nextjs:$IMAGE_TAG
        docker tag nextjs:$IMAGE_TAG 313422618945.dkr.ecr.eu-central-1.amazonaws.com/nextjs:latest
        docker push 313422618945.dkr.ecr.eu-central-1.amazonaws.com/nextjs:$IMAGE_TAG
        docker push 313422618945.dkr.ecr.eu-central-1.amazonaws.com/nextjs:latest

    # - name: Update Docker image tag in HELM chart
    #   working-directory: argocd-apps/nextjs-app
    #   run: |
    #       git_hash=$(git rev-parse --short "$GITHUB_SHA")
    #       tag=$(cat ./values.yaml | grep tag: | awk '{print $2}')
    #       sed -i "s/$tag/${GITHUB_REF##*/}-$git_hash/" ./values.yaml
          
    # - name: Commit and push changes
    #   uses: devops-infra/action-commit-push@v0.3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     commit_message: Version updated
