name: validate-build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    - name: Install dependencies
      working-directory: nextjs/nextjs-app
      run: npm install

    - name: Build
      working-directory: nextjs/nextjs-app
      run: npm run build      